from orders.models import Menu

# add dishes to 'Menu' model on the admin site (creates instances of 'Menu' model)

f = Menu(class_name='Regular Pizza', mtype='pizza', name='Cheese', num_toppings=0, size=True, price=12.70, price_big=17.95)
f.save()
f = Menu(class_name='Regular Pizza', mtype='pizza', name='1 topping', num_toppings=1, size=True, price=13.70, price_big=19.95)
f.save()
f = Menu(class_name='Regular Pizza', mtype='pizza', name='2 toppings', num_toppings=2, size=True, price=15.20, price_big=21.95)
f.save()
f = Menu(class_name='Regular Pizza', mtype='pizza', name='3 toppings', num_toppings=3, size=True, price=16.20, price_big=23.95)
f.save()
f = Menu(class_name='Regular Pizza', mtype='pizza', name='Special', num_toppings=5, size=True, price=17.75, price_big=25.95)
f.save()

f = Menu(class_name='Sicilian Pizza', mtype='pizza', name='Cheese', num_toppings=0, size=True, price=24.45, price_big=38.70)
f.save()
f = Menu(class_name='Sicilian Pizza', mtype='pizza', name='1 topping', num_toppings=1, size=True, price=26.45, price_big=40.70)
f.save()
f = Menu(class_name='Sicilian Pizza', mtype='pizza', name='2 toppings', num_toppings=2, size=True, price=28.45, price_big=42.70)
f.save()
f = Menu(class_name='Sicilian Pizza', mtype='pizza', name='3 toppings', num_toppings=3, size=True, price=29.45, price_big=44.70)
f.save()
f = Menu(class_name='Sicilian Pizza', mtype='pizza', name='Special', num_toppings=5, size=True, price=30.45, price_big=45.70)
f.save()

f = Menu(class_name='Subs', mtype='sub', name='Cheese', num_toppings=1, size=True, price=6.50, price_big=7.95)
f.save()
f = Menu(class_name='Subs', mtype='sub', name='Italian', num_toppings=1, size=True, price=6.50, price_big=7.95)
f.save()
f = Menu(class_name='Subs', mtype='sub', name='Ham + Cheese', num_toppings=1, size=True, price=6.50, price_big=7.95)
f.save()
f = Menu(class_name='Subs', mtype='sub', name='Meatball', num_toppings=1, size=True, price=6.50, price_big=7.95)
f.save()
f = Menu(class_name='Subs', mtype='sub', name='Tuna', num_toppings=1, size=True, price=6.50, price_big=7.95)
f.save()
f = Menu(class_name='Subs', mtype='sub', name='Turkey', num_toppings=1, size=True, price=7.50, price_big=8.50)
f.save()
f = Menu(class_name='Subs', mtype='sub', name='Chicken Parmigiana', num_toppings=1, size=True, price=7.50, price_big=8.50)
f.save()
f = Menu(class_name='Subs', mtype='sub', name='Eggplant Parmigiana', num_toppings=1, size=True, price=6.50, price_big=7.95)
f.save()
f = Menu(class_name='Subs', mtype='subs', name='Steak', num_toppings=4, size=True, price=6.50, price_big=7.95)
f.save()
f = Menu(class_name='Subs', mtype='subs', name='Steak + Cheese', num_toppings=4, size=True, price=6.95, price_big=8.50)
f.save()
f = Menu(class_name='Subs', mtype='sub', name='Sausage, Peppers & Onions', num_toppings=1, size=True, price=8.50, price_big=None)
f.save()
f = Menu(class_name='Subs', mtype='sub', name='Hamburger', num_toppings=1, size=True, price=4.60, price_big=6.95)
f.save()
f = Menu(class_name='Subs', mtype='sub', name='Cheeseburger', num_toppings=1, size=True, price=5.10, price_big=7.45)
f.save()
f = Menu(class_name='Subs', mtype='sub', name='Fried Chicken', num_toppings=1, size=True, price=6.95, price_big=8.50)
f.save()
f = Menu(class_name='Subs', mtype='sub', name='Veggie', num_toppings=1, size=True, price=6.95, price_big=8.50)
f.save()

f = Menu(class_name='Pasta', mtype='pasta', name='Baked Ziti w/Mozzarella', num_toppings=0, size=False, price=6.50)
f.save()
f = Menu(class_name='Pasta', mtype='pasta', name='Baked Ziti w/Meatballs', num_toppings=0, size=False, price=8.75)
f.save()
f = Menu(class_name='Pasta', mtype='pasta', name='Baked Ziti w/Chicken', num_toppings=0, size=False, price=9.75)
f.save()

f = Menu(class_name='Salads', mtype='pasta', name='Garden Salad', num_toppings=0, size=False, price=6.25, price_big=None)
f.save()
f = Menu(class_name='Salads', mtype='pasta', name='Greek Salad', num_toppings=0, size=False, price=8.25, price_big=None)
f.save()
f = Menu(class_name='Salads', mtype='pasta', name='Antipasto', num_toppings=0, size=False, price=8.25, price_big=None)
f.save()
f = Menu(class_name='Salads', mtype='pasta', name='Salad w/Tuna', num_toppings=0, size=False, price=8.25, price_big=None)
f.save()

f = Menu(class_name='Dinner Platters', mtype='pasta', name='Garden Salad', num_toppings=0, size=True, price=40.00, price_big=65.00)
f.save()
f = Menu(class_name='Dinner Platters', mtype='pasta', name='Greek Salad', num_toppings=0, size=True, price=50.00, price_big=75.00)
f.save()
f = Menu(class_name='Dinner Platters', mtype='pasta', name='Antipasto', num_toppings=0, size=True, price=50.00, price_big=75.00)
f.save()
f = Menu(class_name='Dinner Platters', mtype='pasta', name='Baked Ziti', num_toppings=0, size=True, price=40.00, price_big=65.00)
f.save()
f = Menu(class_name='Dinner Platters', mtype='pasta', name='Meatball Parm', num_toppings=0, size=True, price=50.00, price_big=75.00)
f.save()
f = Menu(class_name='Dinner Platters', mtype='pasta', name='Chicken Parm', num_toppings=0, size=True, price=55.00, price_big=85.00)
f.save()